### PR TITLE
fix(api-cors-lambda-crud-dynamodb example): Implement use of NodejsFunction, replaced deprecated API

### LINKED ISSUE #276: typescript - api-cors-lambda-crud-dynamodb  -missing uuid in package.json
### What is the problem?
Error message `Error: Cannot find module 'uuid/v4` when testing `create` function.

### Reproduction Steps
1. deploy the stack as per instructions
2. go to the AWS Console and test `createItem` function with the following test event:

```
{
  "body": "{\"data\":{\"name\":\"foo\"}}"
}
```

3. The result will be that the task timed out. Go to Cloudwatch and view the log for the function. It will complain this: `"Error: Cannot find module 'uuid/v4`

### Environment

  - **CDK CLI Version:** 1.34.1
  - **Example:** api-cors-lambda-crud-dynamodb
  - **Example Version:** createItem function
  - **OS:**  OSX Catalina
  - **Language:** Typescript

### Other information 
The solution requires the uuid package being present inside a `node_modules` of the `src` folder. Currently there is no package.json inside the src folder.

### PR DESCRIPTION
**Pull request by ryparker**
## Summary

This PR changes the following:

- Implement use of NodejsFunction.
- Upgraded lambda runtime from Node 10 -> 14.
- Renamed `/src/` -> `/lambdas/`. This was a personal choice but I believe it makes more sense to label this as anything but `src` since it does not share the same node_modules as the root `package.json`.
- Created `/lambdas/package.json` to define modules required by the lambda functions.
- Added `"postinstall"` script to root package.json which installs the nested `/lambdas/package.json` dependencies after running `npm install` from the root.

Fixes #276, #468, #195
Would have pushed my fixes to #278 however the PR author's branch is protected. 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

File: typescript/api-cors-lambda-crud-dynamodb/index.ts [hunk 1]
```diff
@@ -14,62 +16,94 @@ export class ApiLambdaCrudDynamoDBStack extends cdk.Stack {
...
+       * DESTROY, cdk destroy will delete the table (even if it has data in it)
+       */
       removalPolicy: cdk.RemovalPolicy.DESTROY, // NOT recommended for production code
     });
 
-    const getOneLambda = new lambda.Function(this, 'getOneItemFunction', {
-      code: new lambda.AssetCode('src'),
-      handler: 'get-one.handler',
-      runtime: lambda.Runtime.NODEJS_10_X,
+    const getOneLambda = new NodejsFunction(this, 'getOneItemFunction', {
```
Comment (NGL321) [inline typescript/api-cors-lambda-crud-dynamodb/index.ts:27]: If you are going to use direct component imports (ie. `import { NodejsFunction } from '...';` vs `import * as lambdanode from '...';` and `new NodejsFunction()` vs `new lambdanode.NodejsFunction()`) please do so for all other components (`lambda.Runtime`, `dynamodb.Table`, etc.)

Comment (NGL321) [reply typescript/api-cors-lambda-crud-dynamodb/index.ts:27]: Just to clarify, I think importing components directly is a good approach for examples as it looks cleaner and is considered good practice for projects with few imports.

File: typescript/api-cors-lambda-crud-dynamodb/index.ts [hunk 2]
```diff
@@ -14,62 +16,94 @@ export class ApiLambdaCrudDynamoDBStack extends cdk.Stack {
...
         PRIMARY_KEY: 'itemId'
       }
     });
 
-    const updateOne = new lambda.Function(this, 'updateItemFunction', {
-      code: new lambda.AssetCode('src'),
-      handler: 'update-one.handler',
-      runtime: lambda.Runtime.NODEJS_10_X,
+    const updateOne = new NodejsFunction(this, 'updateItemFunction', {
+      entry: join(__dirname, 'lambdas', 'update-one.ts'), // accepts .js, .jsx, .ts and .tsx files
```
Comment (NGL321) [inline typescript/api-cors-lambda-crud-dynamodb/index.ts:76]: Imo these comments only need to appear on the first occurrence (unless you have strong feelings to the contrary).

File: typescript/api-cors-lambda-crud-dynamodb/lambdas/create.ts [hunk 3]
```diff
@@ -1,13 +1,15 @@
-const AWS = require('aws-sdk');
-const db = new AWS.DynamoDB.DocumentClient();
-const uuidv4 = require('uuid/v4');
+import * as AWS from 'aws-sdk';
```
Comment (NGL321) [inline typescript/api-cors-lambda-crud-dynamodb/lambdas/create.ts:1]: While it contradicts the above comment, I think non-specific imports for the AWS SDK makes sense even if it is contradictory since the SDK is specifically designed for use with general imports.

File: typescript/api-cors-lambda-crud-dynamodb/lambdas/tsconfig.json [hunk 4]
```diff
@@ -0,0 +1,3 @@
+{
+  "extends": "../tsconfig.json"
+}
```
Comment (NGL321) [inline typescript/api-cors-lambda-crud-dynamodb/lambdas/tsconfig.json:3]: New line needed

File: typescript/api-cors-lambda-crud-dynamodb/lambdas/update-one.ts [hunk 5]
```diff
@@ -1,12 +1,14 @@
...
+
 const TABLE_NAME = process.env.TABLE_NAME || '';
 const PRIMARY_KEY = process.env.PRIMARY_KEY || '';
 
+
 const RESERVED_RESPONSE = `Error: You're using AWS reserved keywords as attributes`,
   DYNAMODB_EXECUTION_ERROR = `Error: Execution update, caused a Dynamodb error, please take a look at your CloudWatch Logs.`;
 
-export const handler = async (event: any = {}) : Promise <any> => {
+const db = new AWS.DynamoDB.DocumentClient();
```
Comment (NGL321) [inline typescript/api-cors-lambda-crud-dynamodb/lambdas/update-one.ts:10]: Imo should be separated by line break as was done in previous files.

File: typescript/api-cors-lambda-crud-dynamodb/tsconfig.json [hunk 6]
```diff
@@ -15,7 +19,9 @@
...
-        "strictPropertyInitialization":false
-    }
-}
-
+        "strictPropertyInitialization": false
+    },
+    "include": [
+        "*.ts"
+    ]
+}
```
Comment (NGL321) [inline typescript/api-cors-lambda-crud-dynamodb/tsconfig.json:27]: Another newline

**Review by NGL321 — CHANGES_REQUESTED** [review]
Looks really good. I have a couple notes for improvements, then its ready to merge

**Comment by ryparker** [comment]
> Looks really good. I have a couple notes for improvements, then its ready to merge

Thanks for the suggestions. I implemented all of them and I went a bit further and cleaned up the index.ts file. Specifically the lambda props. Instead of duplicating them in each lambda declaration I stored them in `nodeJsFunctionProps` and reused them in each lambda declaration.

LMK what you think.

File: typescript/api-cors-lambda-crud-dynamodb/lambdas/package.json [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+  "license": "MIT",
+  "devDependencies": {
+    "@types/node": "*",
+    "@types/uuid": "*"
+  },
+  "dependencies": {
+    "aws-sdk": "*",
+    "uuid": "*"
+  }
+}
```
Comment (ryparker) [inline typescript/api-cors-lambda-crud-dynamodb/lambdas/package.json:15]: Strange this should have a newline....

Comment (ryparker) [reply typescript/api-cors-lambda-crud-dynamodb/lambdas/package.json:15]: For some reason I cannot see the newline in GitHub's review UI. However when I click "edit file" I see there is already a new line. LMK if you don't see it during your review @NGL321.

Comment (ryparker) [reply typescript/api-cors-lambda-crud-dynamodb/lambdas/package.json:15]: Did some digging into this and it looks like every file does have a newline char added however you'll only see it in your local editor or when editing the file via GitHub's "edit file" UI. If you want the newline to render in GitHubs "view file" view, then you'll have to add 2 newlines to the bottom of the file.

Is this alright as is? @NGL321

**Review by NGL321 — APPROVED** [review]
Looks great!! 🚀
